#spring.application.name=securityApp
#server.port=8089
#
#spring.security.user.name=Aurindum
#spring.security.user.password=1234

spring.application.name=securityApp
spring.datasource.url=jdbc:postgresql://localhost:5/securityDB
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

server.port=8089

#for inbuilt class object - we make config class and make a method and 
#return manual created object with annotation @bean